version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - aws-ecr/build_and_push_image:
          region: ${AWS_REGION}
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: flask-app
          tag: latest
          requires:
            - build_test
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python -m pytest -v tests/test_script.py
